# Generated by Django 3.1.3 on 2024-06-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tonalidad', models.CharField(max_length=5)),
                ('tipo', models.CharField(max_length=10)),
                ('notas', models.TextField()),
            ],
        ),
    ]
